



Q1: Build Your Personalized Knowledge Base
Take the last two digits of the roll number and create two personalized FAQ entries based on their categories. Combine them with the four given fixed entries and create a final 6-row DataFrame.

In [18]:
import pandas as pd

fixed_entries = [
    {
        "question": "what is the annual fee",
        "answer": "The annual fee is Rs 500.",
        "keywords": "fee cost price charge",
        "category": "billing"
    },
    {
        "question": "how to reset password",
        "answer": "Go to Settings > Reset Password.",
        "keywords": "password reset login",
        "category": "account"
    },
    {
        "question": "what are your working hours",
        "answer": "We are open 9 AM to 5 PM.",
        "keywords": "hours timing open time",
        "category": "general"
    },
    {
        "question": "how can i pay the fee",
        "answer": "You can pay via UPI, card, or net banking.",
        "keywords": "pay payment upi fee",
        "category": "billing"
    }
]

In [19]:
personalized_entries = [
    {
        "question": "how do i update my registered mobile number",
        "answer": "Go to Account Settings and update your registered mobile number.",
        "keywords": "mobile number update account",
        "category": "account"
    },
    {
        "question": "how can i check my latest bill",
        "answer": "You can check your latest bill in the Billing section of your account.",
        "keywords": "bill billing statement payment",
        "category": "billing"
    }
]

In [20]:
all_entries = fixed_entries + personalized_entries

faq_df = pd.DataFrame(all_entries)

faq_df

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,how do i update my registered mobile number,Go to Account Settings and update your registe...,mobile number update account,account
5,how can i check my latest bill,You can check your latest bill in the Billing ...,bill billing statement payment,billing

In [21]:
print(faq_df)

                                      question  \
0                       what is the annual fee
1                        how to reset password
2                  what are your working hours
3                        how can i pay the fee
4  how do i update my registered mobile number
5               how can i check my latest bill

                                              answer  \
0                          The annual fee is Rs 500.
1                   Go to Settings > Reset Password.
2                          We are open 9 AM to 5 PM.
3         You can pay via UPI, card, or net banking.
4  Go to Account Settings and update your registe...
5  You can check your latest bill in the Billing ...

                         keywords category
0           fee cost price charge  billing
1            password reset login  account
2          hours timing open time  general
3             pay payment upi fee  billing
4    mobile number update account  account
5  bill billing statement payment  billing

Q2: Generate and Score a Hypothesis – Implement a scoring function that takes a query string and returns all matching entries ranked by confidence

In [22]:
def score_query(query, df):
    query_words = query.lower().split()
    results = []

    for _, row in df.iterrows():
        keywords = row["keywords"].lower().split()
        score = sum(word in keywords for word in query_words)

        if score > 0:
            results.append({
                "question": row["question"],
                "answer": row["answer"],
                "category": row["category"],
                "score": score
            })

    results = sorted(results, key=lambda x: x["score"], reverse=True)

    return pd.DataFrame(results)

In [23]:
score_query("how can i pay fee", faq_df)

,question,answer,category,score
0,how can i pay the fee,"You can pay via UPI, card, or net banking.",billing,2
1,what is the annual fee,The annual fee is Rs 500.,billing,1

Q3: Write a function same_category(category_name, df) that returns all questions belonging to a given category. Call it using the category of one of the personalized entries from Q1, and print the result.

In [24]:
def same_category(category_name, df):
    return df[df["category"] == category_name]

In [25]:
same_category("account", faq_df)

,question,answer,keywords,category
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
4,how do i update my registered mobile number,Go to Account Settings and update your registe...,mobile number update account,account

Q4: Pick any one entry in your knowledge base. Ask the user to input a new keyword, add it to that entry's keywords, and save the entire updated DataFrame to a CSV file named 1024170040_faq_data.csv.

In [26]:
new_keyword = input("Enter a new keyword: ")

faq_df.loc[0, "keywords"] = faq_df.loc[0, "keywords"] + " " + new_keyword

print("Updated entry:")
print(faq_df.loc[0])

Enter a new keyword: sanvi
Updated entry:
question         what is the annual fee
answer        The annual fee is Rs 500.
keywords    fee cost price charge sanvi
category                        billing
Name: 0, dtype: object

In [27]:
faq_df.to_csv("1024170040_faq_data.csv", index=False)

print("File saved successfully!")

File saved successfully!

Q5: Using groupby, print how many FAQ entries you have per category.

In [28]:
faq_df.groupby("category").size()

category
account    2
billing    3
general    1
dtype: int64

Q6: Modify the Q2 scoring function so that if two or more entries tie for the highest score, it prints all matching entries instead of silently picking one. Demonstrate with one query that produces a tie and one that doesn't.

In [29]:
def score_query_with_ties(query, df):
    query_words = query.lower().split()
    results = []

    for _, row in df.iterrows():
        keywords = row["keywords"].lower().split()
        score = sum(word in keywords for word in query_words)

        if score > 0:
            results.append({
                "question": row["question"],
                "answer": row["answer"],
                "category": row["category"],
                "score": score
            })

    if not results:
        print("No matching entries found.")
        return

    results_df = pd.DataFrame(results)

    max_score = results_df["score"].max()

    top_matches = results_df[results_df["score"] == max_score]

    print("Highest score:", max_score)
    print("Matching FAQ(s):")
    display(top_matches)

In [30]:
score_query_with_ties("fee", faq_df)

Highest score: 1
Matching FAQ(s):

,question,answer,category,score
0,what is the annual fee,The annual fee is Rs 500.,billing,1
1,how can i pay the fee,"You can pay via UPI, card, or net banking.",billing,1

In [31]:
score_query_with_ties("pay upi", faq_df)

Highest score: 2
Matching FAQ(s):

,question,answer,category,score
0,how can i pay the fee,"You can pay via UPI, card, or net banking.",billing,2